"""add_comment_and_video

Revision ID: 0dc8fc9065a4
Revises: 782fc7b75a50
Create Date: 2023-06-09 03:55:53.330008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc8fc9065a4'
down_revision = '782fc7b75a50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url_video', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=2047), nullable=False),
    sa.Column('is_only_register_user', sa.Boolean(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('preview', sa.String(), nullable=False),
    sa.Column('published_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=511), nullable=False),
    sa.Column('published_date', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('url_photo', sa.String(), nullable=False))
    op.add_column('user', sa.Column('register_date', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'register_date')
    op.drop_column('user', 'url_photo')
    op.drop_table('comment')
    op.drop_table('video')
    # ### end Alembic commands ###
