"""fix

Revision ID: 68c0b05df6a7
Revises: 0dc8fc9065a4
Create Date: 2023-06-09 15:16:11.597106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c0b05df6a7'
down_revision = '0dc8fc9065a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
