"""comment

Revision ID: 709a612f0e99
Revises: 828ca65de3dd
Create Date: 2023-06-13 23:31:20.699403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709a612f0e99'
down_revision = '828ca65de3dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_username', table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    # ### end Alembic commands ###
