"""fix3

Revision ID: 828ca65de3dd
Revises: e98caab02249
Create Date: 2023-06-12 18:59:39.203810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828ca65de3dd'
down_revision = 'e98caab02249'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('name', sa.String(), nullable=False))
    op.alter_column('video', 'preview',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('video', 'is_only_register_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('is_only_register_user', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('video', 'preview',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('video', 'name')
    # ### end Alembic commands ###
