"""fix2

Revision ID: e98caab02249
Revises: 68c0b05df6a7
Create Date: 2023-06-09 15:17:44.395870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e98caab02249'
down_revision = '68c0b05df6a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'url_photo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('video', 'description',
               existing_type=sa.VARCHAR(length=2047),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'description',
               existing_type=sa.VARCHAR(length=2047),
               nullable=False)
    op.alter_column('user', 'url_photo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
